EF_Exercise_7/FastFood.Web/ViewModels/Items/CreateItemInputModel.cs
namespace FastFood.Web.ViewModels.Items
{
    using System.ComponentModel.DataAnnotations;

    public class CreateItemInputModel
    {
        [Required]
        [MinLength(3), MaxLength(30)]
        public string Name { get; set; }

        [Range(typeof(decimal), "0.01", "5000")]
        public decimal Price { get; set; }

        public string CategoryName { get; set; }
    }
}

EF_Exercise_7/FastFood.Web/ViewModels/Items/CreateItemViewModel.cs
namespace FastFood.Web.ViewModels.Items
{
    public class CreateItemViewModel
    {
        public string CategoryName { get; set; }
    }
}

EF_Exercise_7/FastFood.Web/ViewModels/Items/ItemsAllViewModels.cs
namespace FastFood.Web.ViewModels.Items
{
    public class ItemsAllViewModels
    {
        public string Name { get; set; }

        public decimal Price { get; set; }

        public string Category { get; set; }
    }
}

EF_Exercise_7/FastFood.Web/Controllers/ItemsController.cs
namespace FastFood.Web.Controllers
{
    using AutoMapper;
    using AutoMapper.QueryableExtensions;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Linq;

    using Data;
    using Models;
    using ViewModels.Categories;
    using ViewModels.Items;

    public class ItemsController : Controller
    {
        private readonly FastFoodContext context;
        private readonly IMapper mapper;

        public ItemsController(FastFoodContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }

        public IActionResult Create()
        {
            var categories = this.context.Categories
                .ProjectTo<CreateItemViewModel>(mapper.ConfigurationProvider)
                .ToList();

            return this.View(categories);
        }

        [HttpPost]
        public IActionResult Create(CreateItemInputModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Error", "Home");
            }

            var item = this.mapper.Map<Item>(model);
            var category = this.context
                .Categories
                .FirstOrDefault(c => c.Name == model.CategoryName);
            item.CategoryId = category.Id;

            this.context.Items.Add(item);
            this.context.SaveChanges();

            return RedirectToAction("All");
        }

        public IActionResult All()
        {
            var items = this.context
                .Items
                .ProjectTo<ItemsAllViewModels>(mapper.ConfigurationProvider)
                .ToList();

            return this.View(items);
        }
    }
}

EF_Exercise_7/FastFood.Web/Views/Items/All.cshtml
@model IList<FastFood.Web.ViewModels.Items.ItemsAllViewModels>

@{
    ViewData["Title"] = "All Items";
}
<h1 class="text-center">All Items</h1>
<hr class="hr-2" />
<table class="table mx-auto">
    <thead>
        <tr class="row">
            <th class="col-md-1">#</th>
            <th class="col-md-2">Name</th>
            <th class="col-md-2">Price</th>
            <th class="col-md-2">Category</th>
        </tr>
    </thead>
    <tbody>
        @for(var i = 0; i < Model.Count(); i++)
    {
        <tr class="row">
            <th class="col-md-1">@(i + 1)</th>
            <td class="col-md-2">@Model[i].Name</td>
            <td class="col-md-2">@Model[i].Price</td>
            <td class="col-md-2">@Model[i].Category</td>
        </tr>
    }
    </tbody>
</table>

EF_Exercise_7/FastFood.Web/Views/Items/Create.cshtml
@model IList<FastFood.Web.ViewModels.Items.CreateItemViewModel>

@{
    ViewData["Title"] = "Create Item";
}
<h1 class="text-center">Create Item</h1>
<hr class="bg-secondary half-width" />
<form class="mx-auto half-width" asp-controller="Items" asp-action="Create" method="post">
    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name" placeholder="Name..." name="name">
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        <input type="number" step="0.01" min="0.01" class="form-control" id="price" placeholder="Price..." name="price">
    </div>
    <div class="form-group">
        <label for="category">Category Name</label>
        <select id="category" class="form-control" name="CategoryName">
            @foreach (var item in Model)
            {
                <option value="@item.CategoryName">@item.CategoryName</option>
            }
        </select>
    </div>
    <hr class="bg-secondary half-width" />
    <div class="button-holder d-flex justify-content-center">
        <button type="submit" class="btn ">Create</button>
    </div>
</form>